# Systems Plugin Metadata
# ========================
# Plugin descriptor for Heracles Systems plugin.

information:
  name: systems
  version: "1.0.0"
  description: System management for servers, workstations, terminals, printers, phones, and mobile devices
  author: Heracles Team
  status: Stable
  license: MIT
  tags:
    - systems
    - infrastructure
    - servers
    - workstations

# LDAP schema files provided by this plugin
ldap_schemas:
  - hrc-systems.schema
  - hrc-systems.ldif

# UI form schema files (JSON Schema)
ui_schemas:
  - schema_server.json
  - schema_workstation.json
  - schema_terminal.json
  - schema_printer.json
  - schema_phone.json
  - schema_mobile.json
  - schema_component.json

# Plugin dependencies
dependencies: []

# Optional dependencies
optional_dependencies:
  - dns
  - dhcp

# Object classes this plugin manages
object_classes:
  - hrcServer
  - hrcWorkstation
  - hrcTerminal
  - hrcPrinter
  - hrcPhone
  - hrcMobilePhone

# Object types this plugin provides (new object management, not tabs)
object_types:
  - server
  - workstation
  - terminal
  - printer
  - phone
  - mobile
  - component

# OID information
oid:
  base: "1.3.6.1.4.1.99999.2"
  registered: false
  note: "Placeholder OID for development. Register with IANA for production."
