#!/bin/bash
# =============================================================================
# Heracles Demo - SSSD Setup for LDAP Authentication
# =============================================================================
# This script configures SSSD (System Security Services Daemon) to authenticate
# users against the Heracles LDAP server. It enables:
#   - NSS (Name Service Switch) for user/group resolution
#   - PAM (Pluggable Authentication Modules) for authentication
#   - Home directory creation on first login
#   - Host-based access control (system trust via hostObject)
#
# Arguments:
#   $1 - LDAP server IP
#   $2 - LDAP port
#   $3 - LDAP base DN
#   $4 - LDAP bind DN
#   $5 - LDAP bind password
#   $6 - Hostname (for host-based access filtering)
# =============================================================================

set -e

LDAP_SERVER_IP="${1:-192.168.56.1}"
LDAP_PORT="${2:-389}"
LDAP_BASE_DN="${3:-dc=heracles,dc=local}"
LDAP_BIND_DN="${4:-cn=admin,dc=heracles,dc=local}"
LDAP_BIND_PASSWORD="${5:-admin_secret}"
HOSTNAME="${6:-$(hostname -s)}"

echo "=============================================="
echo "  Heracles Demo - SSSD Setup"
echo "=============================================="
echo "LDAP Server: ${LDAP_SERVER_IP}:${LDAP_PORT}"
echo "Base DN: ${LDAP_BASE_DN}"
echo "Hostname: ${HOSTNAME}"
echo "=============================================="

# -----------------------------------------------------------------------------
# Install required packages
# -----------------------------------------------------------------------------
echo "[1/6] Installing SSSD and dependencies..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
    sssd \
    sssd-ldap \
    sssd-tools \
    ldap-utils \
    libnss-sss \
    libpam-sss \
    libsss-sudo \
    oddjob-mkhomedir \
    ca-certificates \
    2>/dev/null

# -----------------------------------------------------------------------------
# Configure SSSD
# -----------------------------------------------------------------------------
echo "[2/6] Configuring SSSD..."

cat > /etc/sssd/sssd.conf << EOF
# =============================================================================
# SSSD Configuration for Heracles LDAP
# Generated by Heracles demo provisioning
# =============================================================================

[sssd]
config_file_version = 2
services = nss, pam, sudo
domains = heracles.local

# Debug level (0-10, set higher for troubleshooting)
debug_level = 3

[nss]
filter_groups = root
filter_users = root
# Home directory fallback if not set in LDAP
fallback_homedir = /home/%u
# Default shell if not set in LDAP
default_shell = /bin/bash

[pam]
# Offline authentication (cached credentials)
offline_credentials_expiration = 7
offline_failed_login_attempts = 3
offline_failed_login_delay = 60

[sudo]
# Enable sudo rules from LDAP
# Rules are fetched from ou=sudoers,BASE_DN

[domain/heracles.local]
# Identity provider
id_provider = ldap
auth_provider = ldap
chpass_provider = ldap
sudo_provider = ldap

# LDAP server configuration
ldap_uri = ldap://${LDAP_SERVER_IP}:${LDAP_PORT}
ldap_search_base = ${LDAP_BASE_DN}

# Bind credentials (for searching)
ldap_default_bind_dn = ${LDAP_BIND_DN}
ldap_default_authtok_type = password
ldap_default_authtok = ${LDAP_BIND_PASSWORD}

# TLS/SSL settings (disabled for demo)
ldap_tls_reqcert = never
ldap_id_use_start_tls = false

# Schema type (RFC2307 for posixGroup with memberUid)
ldap_schema = rfc2307

# User search settings
ldap_user_search_base = ou=people,${LDAP_BASE_DN}
ldap_user_object_class = posixAccount
ldap_user_name = uid
ldap_user_uid_number = uidNumber
ldap_user_gid_number = gidNumber
ldap_user_home_directory = homeDirectory
ldap_user_shell = loginShell
ldap_user_gecos = cn

# Group search settings (using posixGroup with memberUid)
ldap_group_search_base = ou=groups,${LDAP_BASE_DN}
ldap_group_object_class = posixGroup
ldap_group_name = cn
ldap_group_gid_number = gidNumber
ldap_group_member = memberUid

# Group nesting not used with RFC2307
ldap_group_nesting_level = 0

# Sudo settings
ldap_sudo_search_base = ou=sudoers,${LDAP_BASE_DN}
ldap_sudo_full_refresh_interval = 86400
ldap_sudo_smart_refresh_interval = 900

# Host-based access control (System Trust via hostObject)
# For demo/testing: use 'permit' to allow all LDAP users
# For production: use 'ldap' with host attribute filtering
# access_provider = ldap
# ldap_access_order = host
# ldap_access_filter = (|(host=*)(host=ALL)(host=${HOSTNAME}))
access_provider = permit

# Cache settings
cache_credentials = true
entry_cache_timeout = 600
ldap_enumeration_refresh_timeout = 300

# Account expiration (shadowAccount support)
ldap_account_expire_policy = shadow
ldap_user_shadow_expire = shadowExpire
ldap_user_shadow_last_change = shadowLastChange

# Performance tuning
ldap_connection_expire_timeout = 600
ldap_opt_timeout = 10

# Debug (set higher for troubleshooting: 0-10)
debug_level = 3
EOF

# Set proper permissions
chmod 600 /etc/sssd/sssd.conf
chown root:root /etc/sssd/sssd.conf

# -----------------------------------------------------------------------------
# Configure NSS (Name Service Switch)
# -----------------------------------------------------------------------------
echo "[3/6] Configuring NSS..."

# Backup original nsswitch.conf
cp /etc/nsswitch.conf /etc/nsswitch.conf.bak

# Update nsswitch.conf to use SSS
cat > /etc/nsswitch.conf << EOF
# /etc/nsswitch.conf
# Name Service Switch configuration file.
# Modified for Heracles LDAP authentication via SSSD

passwd:         files sss
group:          files sss
shadow:         files sss
gshadow:        files

hosts:          files dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis sss
sudoers:        files sss
automount:      sss
EOF

# -----------------------------------------------------------------------------
# Configure PAM for home directory creation
# -----------------------------------------------------------------------------
echo "[4/6] Configuring PAM for automatic home directory creation..."

# Enable mkhomedir in PAM
cat > /usr/share/pam-configs/mkhomedir << EOF
Name: Create home directory on login
Default: yes
Priority: 900
Session-Type: Additional
Session:
    required    pam_mkhomedir.so umask=0077 skel=/etc/skel
EOF

# Update PAM configuration
pam-auth-update --enable mkhomedir --force 2>/dev/null || true

# Alternative: Direct PAM configuration
if ! grep -q "pam_mkhomedir.so" /etc/pam.d/common-session; then
    echo "session required pam_mkhomedir.so skel=/etc/skel umask=0077" >> /etc/pam.d/common-session
fi

# -----------------------------------------------------------------------------
# Configure sudoers to use SSSD
# -----------------------------------------------------------------------------
echo "[5/6] Configuring sudoers for SSSD..."

# Add SSSD to sudoers LDAP lookup
if ! grep -q "sudoers:.*sss" /etc/nsswitch.conf; then
    # Already done above, but verify
    :
fi

# Configure sudo to use SSSD for LDAP
cat > /etc/sudo-ldap.conf << EOF
# sudo LDAP configuration (backup, SSSD is primary)
# This file is used if SSSD is not available
uri ldap://${LDAP_SERVER_IP}:${LDAP_PORT}
sudoers_base ou=sudoers,${LDAP_BASE_DN}
binddn ${LDAP_BIND_DN}
bindpw ${LDAP_BIND_PASSWORD}
ssl no
tls_checkpeer no
EOF

chmod 440 /etc/sudo-ldap.conf

# -----------------------------------------------------------------------------
# Start and enable SSSD
# -----------------------------------------------------------------------------
echo "[6/6] Starting SSSD service..."

# Clear SSSD cache
rm -rf /var/lib/sss/db/* 2>/dev/null || true
rm -rf /var/lib/sss/mc/* 2>/dev/null || true

# Enable and restart SSSD
systemctl enable sssd
systemctl restart sssd

# Wait for SSSD to be ready
sleep 3

# Verify SSSD is running
if systemctl is-active --quiet sssd; then
    echo "✅ SSSD is running"
else
    echo "❌ SSSD failed to start"
    journalctl -u sssd --no-pager -n 20
    exit 1
fi

# -----------------------------------------------------------------------------
# Verification
# -----------------------------------------------------------------------------
echo ""
echo "=============================================="
echo "  SSSD Setup Complete!"
echo "=============================================="
echo ""
echo "Testing LDAP connectivity..."
if ldapsearch -x -H ldap://${LDAP_SERVER_IP}:${LDAP_PORT} -b "${LDAP_BASE_DN}" -D "${LDAP_BIND_DN}" -w "${LDAP_BIND_PASSWORD}" "(objectClass=organization)" dn 2>/dev/null | grep -q "dn:"; then
    echo "✅ LDAP connection successful"
else
    echo "⚠️  LDAP connection test failed (server may not be ready)"
fi

echo ""
echo "To verify LDAP users are visible, run:"
echo "  getent passwd"
echo ""
echo "To test SSH login with an LDAP user, run from host:"
echo "  ssh -i ~/.ssh/id_ed25519 <username>@192.168.56.10"
echo ""
echo "To check SSSD status:"
echo "  sudo systemctl status sssd"
echo "  sudo sssctl domain-status heracles.local"
echo ""
