#!/bin/bash
# =============================================================================
# Heracles Demo - SSH Setup for LDAP Public Keys
# =============================================================================
# This script configures OpenSSH to fetch authorized keys from LDAP using
# the AuthorizedKeysCommand directive. It retrieves public keys stored in
# the sshPublicKey attribute (ldapPublicKey objectClass from openssh-lpk schema).
#
# Arguments:
#   $1 - LDAP server IP
#   $2 - LDAP port
#   $3 - LDAP base DN
#   $4 - LDAP bind DN
#   $5 - LDAP bind password
# =============================================================================

set -e

LDAP_SERVER_IP="${1:-192.168.56.1}"
LDAP_PORT="${2:-389}"
LDAP_BASE_DN="${3:-dc=heracles,dc=local}"
LDAP_BIND_DN="${4:-cn=admin,dc=heracles,dc=local}"
LDAP_BIND_PASSWORD="${5:-admin_secret}"

echo "=============================================="
echo "  Heracles Demo - SSH LDAP Keys Setup"
echo "=============================================="
echo "LDAP Server: ${LDAP_SERVER_IP}:${LDAP_PORT}"
echo "Base DN: ${LDAP_BASE_DN}"
echo "=============================================="

# -----------------------------------------------------------------------------
# Install required packages
# -----------------------------------------------------------------------------
echo "[1/4] Installing SSH and LDAP utilities..."
export DEBIAN_FRONTEND=noninteractive
apt-get install -y -qq \
    openssh-server \
    ldap-utils \
    libsss-sudo \
    2>/dev/null

# -----------------------------------------------------------------------------
# Create SSH LDAP key fetcher script
# -----------------------------------------------------------------------------
echo "[2/4] Creating SSH authorized keys command script..."

cat > /usr/local/bin/ldap-ssh-keys.sh << 'SCRIPT_EOF'
#!/bin/bash
# =============================================================================
# LDAP SSH Public Keys Fetcher
# =============================================================================
# This script is called by OpenSSH's AuthorizedKeysCommand to fetch
# public keys from LDAP for a given username.
#
# Handles LDAP line folding (continuation lines starting with space).
#
# Usage: /usr/local/bin/ldap-ssh-keys.sh <username>
# =============================================================================

CONFIG_FILE="/etc/ssh/ldap-ssh-keys.conf"

if [[ -f "${CONFIG_FILE}" ]]; then
    source "${CONFIG_FILE}"
else
    echo "# Error: Config file not found: ${CONFIG_FILE}" >&2
    exit 1
fi

USERNAME="$1"

if [[ -z "${USERNAME}" ]]; then
    echo "# Error: No username provided" >&2
    exit 1
fi

# Sanitize username (prevent LDAP injection)
if [[ ! "${USERNAME}" =~ ^[a-zA-Z0-9._-]+$ ]]; then
    echo "# Error: Invalid username format" >&2
    exit 1
fi

# Fetch LDAP output and unfold continuation lines
# LDAP line folding: long lines are split with newline + single space
ldapsearch -x \
    -H "ldap://${LDAP_HOST}:${LDAP_PORT}" \
    -D "${LDAP_BIND_DN}" \
    -w "${LDAP_BIND_PASSWORD}" \
    -b "${LDAP_USER_BASE}" \
    -LLL \
    "(uid=${USERNAME})" \
    sshPublicKey 2>/dev/null | \
    awk '
    /^sshPublicKey:/ {
        # Start of a key - extract value after "sshPublicKey: "
        key = $0
        sub(/^sshPublicKey: */, "", key)
        next
    }
    /^ / {
        # Continuation line - append without the leading space
        sub(/^ /, "", $0)
        key = key $0
        next
    }
    key != "" {
        # Not a continuation - print collected key and reset
        print key
        key = ""
    }
    END {
        # Print last key if any
        if (key != "") print key
    }
    '

exit 0
SCRIPT_EOF

chmod 755 /usr/local/bin/ldap-ssh-keys.sh

# Create configuration file for the script
cat > /etc/ssh/ldap-ssh-keys.conf << EOF
# LDAP SSH Keys Configuration
# Generated by Heracles demo provisioning

LDAP_HOST="${LDAP_SERVER_IP}"
LDAP_PORT="${LDAP_PORT}"
LDAP_BASE_DN="${LDAP_BASE_DN}"
LDAP_USER_BASE="ou=people,${LDAP_BASE_DN}"
LDAP_BIND_DN="${LDAP_BIND_DN}"
LDAP_BIND_PASSWORD="${LDAP_BIND_PASSWORD}"
EOF

chmod 644 /etc/ssh/ldap-ssh-keys.conf

# -----------------------------------------------------------------------------
# Configure OpenSSH
# -----------------------------------------------------------------------------
echo "[3/4] Configuring OpenSSH for LDAP keys..."

# Backup original sshd_config
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak

# Create custom configuration
cat > /etc/ssh/sshd_config.d/heracles-ldap.conf << EOF
# =============================================================================
# Heracles LDAP SSH Configuration
# =============================================================================
# This configuration enables SSH public key authentication via LDAP.
# Public keys are stored in the sshPublicKey attribute of user entries.

# Enable public key authentication
PubkeyAuthentication yes

# Fetch authorized keys from LDAP
# %u is replaced with the username
AuthorizedKeysCommand /usr/local/bin/ldap-ssh-keys.sh %u
AuthorizedKeysCommandUser nobody

# Also check local authorized_keys files (fallback)
AuthorizedKeysFile .ssh/authorized_keys

# Password authentication (allow for testing, disable in production)
PasswordAuthentication yes

# Use PAM for authentication (integrates with SSSD)
UsePAM yes

# Allow LDAP users to login
# (SSSD handles user lookup, so we don't need explicit AllowUsers)

# Logging for debugging
LogLevel VERBOSE
EOF

# Ensure sshd_config includes the config directory
if ! grep -q "^Include /etc/ssh/sshd_config.d/\*.conf" /etc/ssh/sshd_config; then
    echo "Include /etc/ssh/sshd_config.d/*.conf" >> /etc/ssh/sshd_config
fi

# Validate SSH configuration
if sshd -t; then
    echo "✅ SSH configuration is valid"
else
    echo "❌ SSH configuration has errors"
    exit 1
fi

# -----------------------------------------------------------------------------
# Restart SSH service
# -----------------------------------------------------------------------------
echo "[4/4] Restarting SSH service..."

systemctl restart sshd

if systemctl is-active --quiet sshd; then
    echo "✅ SSH service is running"
else
    echo "❌ SSH service failed to start"
    journalctl -u sshd --no-pager -n 20
    exit 1
fi

# -----------------------------------------------------------------------------
# Verification
# -----------------------------------------------------------------------------
echo ""
echo "=============================================="
echo "  SSH LDAP Keys Setup Complete!"
echo "=============================================="
echo ""
echo "Testing SSH key fetcher..."
echo "  /usr/local/bin/ldap-ssh-keys.sh testuser"
echo ""
echo "To test SSH login with LDAP keys:"
echo ""
echo "  1. Add your SSH public key to a user in Heracles UI"
echo "     (User > SSH Tab > Add Key)"
echo ""
echo "  2. SSH to this VM:"
echo "     ssh -i ~/.ssh/id_ed25519 <username>@$(hostname -I | awk '{print $2}')"
echo ""
echo "  3. Check SSH logs for debugging:"
echo "     sudo journalctl -u sshd -f"
echo ""
