#!/bin/bash
# =============================================================================
# Heracles Demo - BIND9 DNS Server Setup with LDAP Backend (DLZ)
# =============================================================================
# This script configures BIND9 as an authoritative DNS server for the
# heracles.local domain, fetching zone data from LDAP using the DLZ
# (Dynamically Loadable Zones) LDAP driver.
#
# Arguments:
#   $1 - LDAP server IP
#   $2 - LDAP port
#   $3 - LDAP base DN
#   $4 - LDAP bind DN
#   $5 - LDAP bind password
# =============================================================================

set -e

LDAP_SERVER_IP="${1:-192.168.56.1}"
LDAP_PORT="${2:-389}"
LDAP_BASE_DN="${3:-dc=heracles,dc=local}"
LDAP_BIND_DN="${4:-cn=admin,dc=heracles,dc=local}"
LDAP_BIND_PASSWORD="${5:-admin_secret}"

echo "=============================================="
echo "  Heracles Demo - BIND9 DNS Server Setup"
echo "=============================================="
echo "LDAP Server: ${LDAP_SERVER_IP}:${LDAP_PORT}"
echo "Base DN: ${LDAP_BASE_DN}"
echo "=============================================="

# -----------------------------------------------------------------------------
# Install BIND9
# -----------------------------------------------------------------------------
echo "[1/5] Installing BIND9..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
    bind9 \
    bind9-dnsutils \
    ldap-utils \
    2>/dev/null

# -----------------------------------------------------------------------------
# Configure BIND options
# -----------------------------------------------------------------------------
echo "[2/5] Configuring BIND9 options..."

# Get the host's default DNS for forwarding (from VirtualBox NAT)
HOST_DNS=$(grep -m1 nameserver /etc/resolv.conf | awk '{print $2}')
if [ -z "$HOST_DNS" ] || [ "$HOST_DNS" = "127.0.0.1" ]; then
    HOST_DNS="8.8.8.8"
fi

cat > /etc/bind/named.conf.options << EOF
// =============================================================================
// BIND9 Options - Heracles DNS Server
// Generated by Heracles demo provisioning
// =============================================================================

options {
    directory "/var/cache/bind";

    // Forward unknown queries to host resolver
    forwarders {
        ${HOST_DNS};
        8.8.4.4;
    };
    forward only;

    // Listen on all interfaces
    listen-on { any; };
    listen-on-v6 { any; };

    // Allow queries from demo network
    allow-query { 
        localhost;
        192.168.56.0/24;
        10.0.0.0/8;
    };

    // Allow recursion for local clients
    allow-recursion {
        localhost;
        192.168.56.0/24;
    };

    // DNSSEC validation (auto for production, but disabled for demo simplicity)
    dnssec-validation no;

    // Query source for outbound queries
    query-source address * port *;

    // Reduce logging noise
    minimal-responses yes;
};

// Logging configuration
logging {
    channel default_log {
        file "/var/log/named/default.log" versions 3 size 5m;
        severity info;
        print-time yes;
        print-severity yes;
        print-category yes;
    };

    channel query_log {
        file "/var/log/named/query.log" versions 3 size 10m;
        severity debug;
        print-time yes;
    };

    category default { default_log; };
    category queries { query_log; };
};
EOF

# Create log directory
mkdir -p /var/log/named
chown bind:bind /var/log/named

# -----------------------------------------------------------------------------
# Configure LDAP DLZ for heracles.local zone
# -----------------------------------------------------------------------------
echo "[3/5] Configuring zone files..."

# Use static zone files (LDAP DLZ not available in Debian Bookworm)
# Zones are synced from LDAP using the ldap-dns-sync.sh script
cat > /etc/bind/named.conf.local << EOF
// =============================================================================
// BIND9 Local Zones - Heracles DNS Server
// Generated by Heracles demo provisioning
// =============================================================================

// Forward zone: heracles.local
zone "heracles.local" {
    type master;
    file "/etc/bind/zones/db.heracles.local";
    allow-update { none; };
};

// Reverse zone: 192.168.56.0/24
zone "56.168.192.in-addr.arpa" {
    type master;
    file "/etc/bind/zones/db.56.168.192";
    allow-update { none; };
};
EOF

# -----------------------------------------------------------------------------
# Create zone files from LDAP or use static fallback
# -----------------------------------------------------------------------------
echo "[4/5] Creating zone files..."

mkdir -p /etc/bind/zones

# Create LDAP sync script for future updates
cat > /usr/local/bin/ldap-dns-sync.sh << 'SYNCEOF'
#!/bin/bash
# Sync DNS zones from LDAP to BIND zone files
# Usage: ldap-dns-sync.sh [LDAP_SERVER] [LDAP_PORT] [BASE_DN] [BIND_DN] [PASSWORD]

LDAP_SERVER="${1:-192.168.56.1}"
LDAP_PORT="${2:-389}"
BASE_DN="${3:-dc=heracles,dc=local}"
BIND_DN="${4:-cn=admin,dc=heracles,dc=local}"
PASSWORD="${5:-admin_secret}"

ZONE_DIR="/etc/bind/zones"
SERIAL=$(date +%Y%m%d%H)

# Helper to unfold LDAP line continuations
ldap_unfold() {
    sed ':a;N;$!ba;s/\n //g'
}

# Generate forward zone
generate_forward_zone() {
    local zone="$1"
    local file="$ZONE_DIR/db.$zone"
    local tmpfile=$(mktemp)
    
    echo "; Zone file for $zone - generated from LDAP" > "$file"
    echo "; Generated: $(date)" >> "$file"
    echo "\$TTL 86400" >> "$file"
    
    # Get zone apex (SOA, NS, MX)
    ldapsearch -x -H "ldap://${LDAP_SERVER}:${LDAP_PORT}" -D "$BIND_DN" -w "$PASSWORD" \
        -b "zoneName=$zone,ou=dns,$BASE_DN" "(relativeDomainName=@)" -LLL 2>/dev/null | ldap_unfold > "$tmpfile"
    
    soa_record=$(grep "^sOARecord:" "$tmpfile" | sed 's/sOARecord: //')
    ns_record=$(grep "^nSRecord:" "$tmpfile" | sed 's/nSRecord: //')
    mx_record=$(grep "^mXRecord:" "$tmpfile" | sed 's/mXRecord: //')
    
    if [ -n "$soa_record" ]; then
        echo "@       IN      SOA     $soa_record" >> "$file"
    else
        echo "@       IN      SOA     ns1.$zone. admin.$zone. $SERIAL 3600 1800 604800 86400" >> "$file"
    fi
    
    if [ -n "$ns_record" ]; then
        echo "@       IN      NS      $ns_record" >> "$file"
    fi
    
    if [ -n "$mx_record" ]; then
        echo "@       IN      MX      $mx_record" >> "$file"
    fi
    
    # Get all other records
    ldapsearch -x -H "ldap://${LDAP_SERVER}:${LDAP_PORT}" -D "$BIND_DN" -w "$PASSWORD" \
        -b "zoneName=$zone,ou=dns,$BASE_DN" "(&(objectClass=dNSZone)(!(relativeDomainName=@)))" -LLL 2>/dev/null | ldap_unfold > "$tmpfile"
    
    local current_name=""
    while IFS= read -r line; do
        case "$line" in
            relativeDomainName:*)
                current_name=$(echo "$line" | sed 's/relativeDomainName: //')
                ;;
            aRecord:*)
                ip=$(echo "$line" | sed 's/aRecord: //')
                echo "$current_name       IN      A       $ip" >> "$file"
                ;;
            aAAARecord:*)
                ip=$(echo "$line" | sed 's/aAAARecord: //')
                echo "$current_name       IN      AAAA    $ip" >> "$file"
                ;;
            cNAMERecord:*)
                target=$(echo "$line" | sed 's/cNAMERecord: //')
                echo "$current_name       IN      CNAME   $target" >> "$file"
                ;;
            mXRecord:*)
                mx=$(echo "$line" | sed 's/mXRecord: //')
                echo "$current_name       IN      MX      $mx" >> "$file"
                ;;
            tXTRecord:*)
                txt=$(echo "$line" | sed 's/tXTRecord: //')
                echo "$current_name       IN      TXT     \"$txt\"" >> "$file"
                ;;
            pTRRecord:*)
                ptr=$(echo "$line" | sed 's/pTRRecord: //')
                echo "$current_name       IN      PTR     $ptr" >> "$file"
                ;;
            sRVRecord:*)
                srv=$(echo "$line" | sed 's/sRVRecord: //')
                echo "$current_name       IN      SRV     $srv" >> "$file"
                ;;
        esac
    done < "$tmpfile"
    
    rm -f "$tmpfile"
    chown bind:bind "$file"
    echo "[+] Generated $file"
}

# Generate reverse zone
generate_reverse_zone() {
    local zone="$1"
    local file="$ZONE_DIR/db.$(echo $zone | sed 's/.in-addr.arpa//')"
    local tmpfile=$(mktemp)
    
    echo "; Reverse zone file for $zone - generated from LDAP" > "$file"
    echo "; Generated: $(date)" >> "$file"
    echo "\$TTL 86400" >> "$file"
    
    # Get zone apex
    ldapsearch -x -H "ldap://${LDAP_SERVER}:${LDAP_PORT}" -D "$BIND_DN" -w "$PASSWORD" \
        -b "zoneName=$zone,ou=dns,$BASE_DN" "(relativeDomainName=@)" -LLL 2>/dev/null | ldap_unfold > "$tmpfile"
    
    soa_record=$(grep "^sOARecord:" "$tmpfile" | sed 's/sOARecord: //')
    ns_record=$(grep "^nSRecord:" "$tmpfile" | sed 's/nSRecord: //')
    
    if [ -n "$soa_record" ]; then
        echo "@       IN      SOA     $soa_record" >> "$file"
    else
        echo "@       IN      SOA     ns1.heracles.local. admin.heracles.local. $SERIAL 3600 1800 604800 86400" >> "$file"
    fi
    
    if [ -n "$ns_record" ]; then
        echo "@       IN      NS      $ns_record" >> "$file"
    fi
    
    # Get PTR records
    ldapsearch -x -H "ldap://${LDAP_SERVER}:${LDAP_PORT}" -D "$BIND_DN" -w "$PASSWORD" \
        -b "zoneName=$zone,ou=dns,$BASE_DN" "(pTRRecord=*)" -LLL 2>/dev/null | ldap_unfold > "$tmpfile"
    
    local current_name=""
    while IFS= read -r line; do
        case "$line" in
            relativeDomainName:*)
                current_name=$(echo "$line" | sed 's/relativeDomainName: //')
                [ "$current_name" = "@" ] && continue
                ;;
            pTRRecord:*)
                ptr=$(echo "$line" | sed 's/pTRRecord: //')
                echo "$current_name       IN      PTR     $ptr" >> "$file"
                ;;
        esac
    done < "$tmpfile"
    
    rm -f "$tmpfile"
    chown bind:bind "$file"
    echo "[+] Generated $file"
}

echo "Syncing DNS zones from LDAP..."
generate_forward_zone "heracles.local"
generate_reverse_zone "56.168.192.in-addr.arpa"

# Validate and reload BIND
echo "Validating zone files..."
named-checkzone heracles.local "$ZONE_DIR/db.heracles.local" && \
named-checkzone 56.168.192.in-addr.arpa "$ZONE_DIR/db.56.168.192" && \
(rndc reload 2>/dev/null || systemctl reload named 2>/dev/null) && \
echo "DNS zones reloaded successfully" || echo "Zone validation failed"
SYNCEOF

chmod +x /usr/local/bin/ldap-dns-sync.sh

# Try to sync from LDAP, fall back to static if it fails
echo "    Attempting to sync zones from LDAP..."
if ldapsearch -x -H "ldap://${LDAP_SERVER_IP}:${LDAP_PORT}" -D "${LDAP_BIND_DN}" -w "${LDAP_BIND_PASSWORD}" \
    -b "ou=dns,${LDAP_BASE_DN}" "(objectClass=dNSZone)" dn 2>/dev/null | grep -q "zoneName=heracles.local"; then
    
    echo "[+] LDAP zones found, syncing..."
    /usr/local/bin/ldap-dns-sync.sh "${LDAP_SERVER_IP}" "${LDAP_PORT}" "${LDAP_BASE_DN}" "${LDAP_BIND_DN}" "${LDAP_BIND_PASSWORD}"
else
    echo "[!] LDAP zones not found, using static zone files..."
    
    # Create static zone files
    cat > /etc/bind/zones/db.heracles.local << 'EOF'
; =============================================================================
; heracles.local zone file (static)
; =============================================================================
$TTL    86400
@       IN      SOA     ns1.heracles.local. admin.heracles.local. (
                        2026012701      ; Serial (YYYYMMDDNN)
                        3600            ; Refresh (1 hour)
                        1800            ; Retry (30 min)
                        604800          ; Expire (1 week)
                        86400 )         ; Minimum TTL (1 day)

; Nameservers
@       IN      NS      ns1.heracles.local.
@       IN      MX      10 mail.heracles.local.

; A records for infrastructure
ns1             IN      A       192.168.56.20
ldap            IN      A       192.168.56.1
server1         IN      A       192.168.56.10
workstation1    IN      A       192.168.56.11
mail            IN      A       192.168.56.1

; CNAME aliases
dns             IN      CNAME   ns1.heracles.local.
api             IN      CNAME   ldap.heracles.local.
ui              IN      CNAME   ldap.heracles.local.
EOF

    cat > /etc/bind/zones/db.56.168.192 << 'EOF'
; =============================================================================
; Reverse DNS zone for 192.168.56.0/24 (static)
; =============================================================================
$TTL    86400
@       IN      SOA     ns1.heracles.local. admin.heracles.local. (
                        2026012701      ; Serial
                        3600            ; Refresh
                        1800            ; Retry
                        604800          ; Expire
                        86400 )         ; Minimum TTL

; Nameservers
@       IN      NS      ns1.heracles.local.

; PTR records
1       IN      PTR     ldap.heracles.local.
10      IN      PTR     server1.heracles.local.
11      IN      PTR     workstation1.heracles.local.
20      IN      PTR     ns1.heracles.local.
EOF
fi

chown -R bind:bind /etc/bind/zones

# -----------------------------------------------------------------------------
# Validate and start BIND9
# -----------------------------------------------------------------------------
echo "[5/5] Validating and starting BIND9..."

# Validate zone files
echo "[*] Validating zone files..."
named-checkzone heracles.local /etc/bind/zones/db.heracles.local
named-checkzone 56.168.192.in-addr.arpa /etc/bind/zones/db.56.168.192

# Validate BIND configuration
echo "[*] Validating BIND9 configuration..."
named-checkconf

# Enable and start BIND9
systemctl enable named
systemctl restart named

# Wait for BIND to start
sleep 2

# Test DNS resolution
echo ""
echo "=============================================="
echo "  BIND9 DNS Server Ready!"
echo "=============================================="
echo ""
echo "Testing DNS resolution..."
if dig @127.0.0.1 ns1.heracles.local +short 2>/dev/null | grep -q "192.168.56.20"; then
    echo "[+] ns1.heracles.local -> $(dig @127.0.0.1 ns1.heracles.local +short)"
else
    echo "[!] DNS resolution test failed"
fi

if dig @127.0.0.1 server1.heracles.local +short 2>/dev/null | grep -q "192.168.56.10"; then
    echo "[+] server1.heracles.local -> $(dig @127.0.0.1 server1.heracles.local +short)"
fi

if dig @127.0.0.1 -x 192.168.56.10 +short 2>/dev/null | grep -q "server1"; then
    echo "[+] 192.168.56.10 -> $(dig @127.0.0.1 -x 192.168.56.10 +short)"
fi

echo ""
echo "DNS Server: 192.168.56.20"
echo "Zone: heracles.local"
echo ""
echo "Test commands:"
echo "  dig @192.168.56.20 ns1.heracles.local"
echo "  dig @192.168.56.20 server1.heracles.local"
echo "  dig @192.168.56.20 -x 192.168.56.10"
echo ""
echo "To sync zones from LDAP (after making changes):"
echo "  /usr/local/bin/ldap-dns-sync.sh"
echo ""
