# ============================================================================
# Heracles - Help System
# ============================================================================
# Auto-generated help from target comments

.PHONY: help

# Default target
.DEFAULT_GOAL := help

# Display help
help:
	@echo ""
	@echo "$(CYAN)╔═══════════════════════════════════════════════════════════════════════╗$(NC)"
	@echo "$(CYAN)║$(NC)                          $(BOLD)HERACLES$(NC)                                      $(CYAN)║$(NC)"
	@echo "$(CYAN)║$(NC)                    $(DIM)Identity Management System$(NC)                          $(CYAN)║$(NC)"
	@echo "$(CYAN)╚═══════════════════════════════════════════════════════════════════════╝$(NC)"
	@echo ""
	@echo "$(BOLD)🚀 Quick Start$(NC)"
	@echo "  $(GREEN)make dev-infra$(NC)       Start infrastructure (LDAP, PostgreSQL, Redis)"
	@echo "  $(GREEN)make bootstrap$(NC)       Initialize LDAP with base structure"
	@echo "  $(GREEN)make api$(NC)             Start API development server"
	@echo "  $(GREEN)make ui$(NC)              Start UI development server"
	@echo ""
	@echo "$(BOLD)🐳 Docker Commands$(NC)"
	@echo "  $(GREEN)make dev$(NC)             Start full development environment"
	@echo "  $(GREEN)make prod$(NC)            Start production environment"
	@echo "  $(GREEN)make stop$(NC)            Stop all services"
	@echo "  $(GREEN)make clean$(NC)           Remove all containers and volumes"
	@echo "  $(GREEN)make logs$(NC)            View all container logs"
	@echo "  $(GREEN)make ldap-schemas$(NC)    Load custom LDAP schemas"
	@echo "  $(GREEN)make ldap-schemas-list$(NC) List available/loaded schemas"
	@echo ""
	@echo "$(BOLD)🏗️  Docker Build$(NC)"
	@echo "  $(GREEN)make docker-build$(NC)    Build all Docker images"
	@echo "  $(GREEN)make docker-build-api$(NC) Build API Docker image"
	@echo "  $(GREEN)make docker-build-ui$(NC)  Build UI Docker image"
	@echo "  $(GREEN)make docker-rebuild$(NC)  Rebuild all images (no cache)"
	@echo "  $(GREEN)make docker-rebuild-restart$(NC) Rebuild and restart"
	@echo "  $(GREEN)make docker-pull$(NC)     Pull latest base images"
	@echo ""
	@echo "$(BOLD)🔧 API Development$(NC)"
	@echo "  $(GREEN)make api$(NC)             Start API server with hot reload"
	@echo "  $(GREEN)make api-install$(NC)     Install API dependencies"
	@echo "  $(GREEN)make api-test$(NC)        Run API tests"
	@echo "  $(GREEN)make api-lint$(NC)        Lint API code"
	@echo "  $(GREEN)make api-format$(NC)      Format API code"
	@echo ""
	@echo "$(BOLD)🖥️  UI Development$(NC)"
	@echo "  $(GREEN)make ui$(NC)              Start UI dev server with hot reload"
	@echo "  $(GREEN)make ui-install$(NC)      Install UI dependencies"
	@echo "  $(GREEN)make ui-build$(NC)        Build UI for production"
	@echo "  $(GREEN)make ui-lint$(NC)         Lint UI code"
	@echo "  $(GREEN)make ui-test$(NC)         Run UI tests"
	@echo ""
	@echo "$(BOLD)🦀 Rust Core$(NC)"
	@echo "  $(GREEN)make core$(NC)            Build Rust core (debug)"
	@echo "  $(GREEN)make core-release$(NC)    Build Rust core (release)"
	@echo "  $(GREEN)make core-test$(NC)       Run Rust tests"
	@echo "  $(GREEN)make core-lint$(NC)       Lint Rust code (clippy)"
	@echo ""
	@echo "$(BOLD)🧩 Plugins$(NC)"
	@echo "  $(GREEN)make plugins-install$(NC) Install plugins in dev mode"
	@echo "  $(GREEN)make plugins-test$(NC)    Run plugins tests"
	@echo "  $(GREEN)make plugins-lint$(NC)    Lint plugins code"
	@echo ""
	@echo "$(BOLD)🔄 Combined Commands$(NC)"
	@echo "  $(GREEN)make install$(NC)         Install all dependencies"
	@echo "  $(GREEN)make test$(NC)            Run all tests"
	@echo "  $(GREEN)make lint$(NC)            Lint all code"
	@echo "  $(GREEN)make format$(NC)          Format all code"
	@echo "  $(GREEN)make check$(NC)           Full check (lint + typecheck + test)"
	@echo "  $(GREEN)make build$(NC)           Build for production"
	@echo ""
	@echo "$(BOLD)📝 Environment$(NC)"
	@echo "  $(DIM)API Port:$(NC)           $(API_PORT)"
	@echo "  $(DIM)UI Port:$(NC)            $(UI_PORT)"
	@echo "  $(DIM)LDAP Port:$(NC)          $(LDAP_PORT)"
	@echo "  $(DIM)phpLDAPadmin:$(NC)       $(PHPLDAPADMIN_PORT)"
	@echo ""
