# DNS Plugin Metadata
# ====================
# Plugin descriptor for Heracles DNS plugin.

information:
  name: dns
  version: "1.0.0"
  description: DNS zone and record management via dNSZone objectClass
  author: Heracles Team
  status: Stable
  license: MIT
  tags:
    - dns
    - infrastructure
    - network

# LDAP schema files provided by this plugin
ldap_schemas:
  - dnszone.schema
  - dnszone.ldif

# UI form schema files (JSON Schema)
ui_schemas: []

# Plugin dependencies
dependencies: []

# Optional dependencies
optional_dependencies:
  - systems

# Object classes this plugin manages
object_classes:
  - dNSZone

# Object types this plugin provides (new object management)
object_types:
  - dns_zone
  - dns_record

# OID information
oid:
  base: "1.3.6.1.4.1.2428.20"
  registered: true
  owner: "PowerDNS/RFC"
  url: "https://doc.powerdns.com/authoritative/backends/ldap.html"
