#!/usr/bin/env bash
# =============================================================================
# Heracles — Interactive Installation Wizard
# =============================================================================
# Usage: ./scripts/install.sh
# Creates .env from production example, generates secrets, and starts services.
# =============================================================================

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

header() {
  echo ""
  echo -e "${CYAN}╔══════════════════════════════════════════════════════════════╗${NC}"
  echo -e "${CYAN}║${NC}  ${BOLD}$1${NC}"
  echo -e "${CYAN}╚══════════════════════════════════════════════════════════════╝${NC}"
}

info()    { echo -e "  ${BLUE}ℹ${NC}  $1"; }
success() { echo -e "  ${GREEN}✓${NC}  $1"; }
warn()    { echo -e "  ${YELLOW}⚠${NC}  $1"; }
error()   { echo -e "  ${RED}✗${NC}  $1"; }
prompt()  { echo -en "  ${BOLD}?${NC}  $1: "; }

generate_secret() { openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | base64 | tr -d '\n/+=' | head -c 64; }
generate_password() { openssl rand -base64 24 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -d '\n/+=' | head -c 32; }

# ─── Pre-flight checks ───────────────────────────────────────────────────────

header "Heracles Installation Wizard"
echo ""
echo -e "  Welcome to ${BOLD}Heracles${NC} — Modern LDAP Identity Management"
echo "  This wizard will set up your environment and start all services."
echo ""

# Check commands
for cmd in docker openssl; do
  if ! command -v "$cmd" &>/dev/null; then
    error "'$cmd' is required but not found. Please install it first."
    exit 1
  fi
done

if ! docker compose version &>/dev/null; then
  error "'docker compose' plugin is required. Please update Docker."
  exit 1
fi
success "Docker + Docker Compose detected"

# Check if .env already exists
if [[ -f .env ]]; then
  warn ".env file already exists."
  prompt "Overwrite? (y/N)"
  read -r overwrite
  if [[ "${overwrite,,}" != "y" ]]; then
    info "Keeping existing .env — skipping configuration."
    SKIP_CONFIG=true
  else
    SKIP_CONFIG=false
  fi
else
  SKIP_CONFIG=false
fi

# ─── Configuration ───────────────────────────────────────────────────────────

if [[ "${SKIP_CONFIG:-false}" != "true" ]]; then
  header "Organization Configuration"

  prompt "Organization name (default: MyOrganisation)"
  read -r ORG_NAME
  ORG_NAME="${ORG_NAME:-MyOrganisation}"

  prompt "Domain (default: heracles.local)"
  read -r DOMAIN
  DOMAIN="${DOMAIN:-heracles.local}"

  # Derive base DN from domain
  BASE_DN=""
  IFS='.' read -ra PARTS <<< "$DOMAIN"
  for part in "${PARTS[@]}"; do
    [[ -n "$BASE_DN" ]] && BASE_DN="${BASE_DN},"
    BASE_DN="${BASE_DN}dc=${part}"
  done

  success "Organization: ${ORG_NAME}"
  success "Domain: ${DOMAIN} (Base DN: ${BASE_DN})"

  header "Admin Configuration"

  prompt "Admin username (default: hrc-admin)"
  read -r ADMIN_USER
  ADMIN_USER="${ADMIN_USER:-hrc-admin}"

  prompt "Admin password (leave blank to auto-generate)"
  read -rs ADMIN_PASS
  echo ""
  if [[ -z "$ADMIN_PASS" ]]; then
    ADMIN_PASS=$(generate_password)
    info "Auto-generated admin password: ${ADMIN_PASS}"
  fi

  header "Generating Secrets"

  LDAP_ADMIN_PW=$(generate_password)
  LDAP_CONFIG_PW=$(generate_password)
  POSTGRES_PW=$(generate_password)
  REDIS_PW=$(generate_password)
  SECRET_KEY=$(generate_secret)

  success "LDAP admin password generated"
  success "PostgreSQL password generated"
  success "Redis password generated"
  success "JWT secret key generated"

  header "Deployment Mode"

  echo "  1) Development  (source mounts, hot reload, debug=true)"
  echo "  2) Production   (pre-built images, TLS, hardened)"
  prompt "Select mode (default: 1)"
  read -r MODE_CHOICE
  MODE_CHOICE="${MODE_CHOICE:-1}"

  if [[ "$MODE_CHOICE" == "2" ]]; then
    DEPLOY_MODE="prod"
    COMPOSE_FILE="docker-compose.prod.yml"
  else
    DEPLOY_MODE="dev"
    COMPOSE_FILE="docker-compose.yml"
  fi

  # ─── Write .env ──────────────────────────────────────────────────────────

  header "Writing .env"

  cat > .env <<EOF
# =============================================================================
# Heracles Environment — Generated by install wizard on $(date -Iseconds)
# =============================================================================

# LDAP
LDAP_ORGANISATION=${ORG_NAME}
LDAP_DOMAIN=${DOMAIN}
LDAP_BASE_DN=${BASE_DN}
LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PW}
LDAP_CONFIG_PASSWORD=${LDAP_CONFIG_PW}
LDAP_BIND_DN=cn=admin,${BASE_DN}
LDAP_POOL_SIZE=10

# Admin User
HRC_ADMIN_USER=${ADMIN_USER}
HRC_ADMIN_PASSWORD=${ADMIN_PASS}
HRC_ADMIN_UID=10000
HRC_ADMIN_GID=10000

# PostgreSQL
POSTGRES_DB=heracles
POSTGRES_USER=heracles
POSTGRES_PASSWORD=${POSTGRES_PW}

# Redis
REDIS_PASSWORD=${REDIS_PW}

# Security
SECRET_KEY=${SECRET_KEY}
ACCESS_TOKEN_EXPIRE_MINUTES=30
REFRESH_TOKEN_EXPIRE_DAYS=7

# API
DEBUG=$([[ "$DEPLOY_MODE" == "dev" ]] && echo "true" || echo "false")
LOG_LEVEL=$([[ "$DEPLOY_MODE" == "dev" ]] && echo "DEBUG" || echo "INFO")
API_HOST=0.0.0.0
API_PORT=8000

# Deploy mode
COMPOSE_FILE=${COMPOSE_FILE}
EOF

  success ".env created"
fi

# ─── Start Services ──────────────────────────────────────────────────────────

header "Starting Infrastructure"

COMPOSE_CMD="docker compose"
if [[ -f "${COMPOSE_FILE:-.}" ]]; then
  COMPOSE_CMD="docker compose -f $COMPOSE_FILE"
fi

info "Starting LDAP, PostgreSQL, Redis..."
$COMPOSE_CMD up -d ldap postgres redis 2>/dev/null || docker compose up -d ldap postgres redis

# Wait for services to be healthy
info "Waiting for services to be ready..."
MAX_WAIT=60
ELAPSED=0
while [[ $ELAPSED -lt $MAX_WAIT ]]; do
  if docker compose exec -T postgres pg_isready -q 2>/dev/null; then
    break
  fi
  sleep 2
  ELAPSED=$((ELAPSED + 2))
  echo -ne "\r  ${BLUE}ℹ${NC}  Waiting... (${ELAPSED}s)"
done
echo ""
success "Infrastructure ready"

header "Bootstrapping LDAP"

if [[ -x scripts/ldap-bootstrap.sh ]]; then
  bash scripts/ldap-bootstrap.sh init 2>/dev/null && success "LDAP structure initialized" || warn "LDAP bootstrap skipped (may already be initialized)"
  bash scripts/ldap-bootstrap.sh schemas 2>/dev/null && success "Schemas loaded" || warn "Schema loading skipped"
else
  warn "ldap-bootstrap.sh not found — skip LDAP bootstrap"
fi

header "Starting All Services"

$COMPOSE_CMD up -d 2>/dev/null || docker compose up -d

# Wait a moment for all services to start
sleep 5

header "Seeding Configuration"

docker compose exec -T api python -m heracles_api.core.seed 2>/dev/null && success "Configuration seeded" || warn "Seed skipped (API may still be starting)"

# ─── Summary ─────────────────────────────────────────────────────────────────

header "Installation Complete!"

echo ""
echo -e "  ${GREEN}✓${NC}  Heracles is running!"
echo ""
echo -e "  ${BOLD}Access Points:${NC}"
echo -e "    UI:             ${CYAN}http://localhost:3000${NC}"
echo -e "    API:            ${CYAN}http://localhost:8000/api/v1${NC}"
echo -e "    API Docs:       ${CYAN}http://localhost:8000/docs${NC}"
echo -e "    phpLDAPadmin:   ${CYAN}http://localhost:8080${NC}"
echo ""
echo -e "  ${BOLD}Credentials:${NC}"
echo -e "    Username:       ${CYAN}${ADMIN_USER:-hrc-admin}${NC}"
echo -e "    Password:       ${CYAN}(see .env → HRC_ADMIN_PASSWORD)${NC}"
echo ""
echo -e "  ${BOLD}Useful commands:${NC}"
echo "    make logs           — View service logs"
echo "    make shell s=api    — API container shell"
echo "    make down           — Stop all services"
echo "    make clean          — Remove everything (including data)"
echo ""
